### ISSUE TITLE
Start game button

### ISSUE THREAD

**Issue by TomFearn** [TomFearn/Block-Flow#9]
**User Story: As a user I want to be able to start the game when I choose not when the webpage loads.**

**Acceptance Criteria:**

- [ ] The game does not automatically start when the webpage loads.
- [ ] A "Start Game" button is displayed for the user to begin the game.
- [ ] Clicking the "Start Game" button starts the game.

**Tasks**

- [ ] Create a "Start Game" button in the UI.
- [ ] Prevent game logic from running on page load.
- [ ] Implement functionality to start the game when the button is clicked.
